# use the shared Yast defaults
inherit_from:
  - /usr/share/YaST2/data/devtools/data/rubocop-1.24.1_yast_style.yml

# this needs more testing if we can have frozen string literals
Style/FrozenStringLiteralComment:
  Enabled: false

Naming/MethodName:
  Enabled: false

Naming/VariableName:
  Enabled: false

# Offense count: 24
# Configuration parameters: CountComments, ExcludedMethods.
# ExcludedMethods: refine
Metrics/BlockLength:
  Max: 350

# Offense count: 5
# Configuration parameters: CountBlocks.
Metrics/BlockNesting:
  Max: 4

# Offense count: 1
# Configuration parameters: CountComments.
Metrics/ModuleLength:
  Max: 1400

# Offense count: 2
# Configuration parameters: CountKeywordArgs.
Metrics/ParameterLists:
  Max: 7

# Offense count: 1
Metrics/AbcSize:
  Max: 339

# Offense count: 1
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 909

# Offense count: 1
Metrics/CyclomaticComplexity:
  Max: 57

# Offense count: 1
# Configuration parameters: CountComments, ExcludedMethods.
Metrics/MethodLength:
  Max: 372

# Offense count: 1
Metrics/PerceivedComplexity:
  Max: 63

# Offense count: 2
# Configuration parameters: ExpectMatchingDefinition, Regex, IgnoreExecutableScripts, AllowedAcronyms.
# AllowedAcronyms: CLI, DSL, ACL, API, ASCII, CPU, CSS, DNS, EOF, GUID, HTML, HTTP, HTTPS, ID, IP, JSON, LHS, QPS, RAM, RHS, RPC, SLA, SMTP, SQL, SSH, TCP, TLS, TTL, UDP, UI, UID, UUID, URI, URL, UTF8, VM, XML, XMPP, XSRF, XSS
Naming/FileName:
  Exclude:
    - 'src/clients/nis-client.rb'
    - 'src/modules/Nis.rb'

# Offense count: 1
# Configuration parameters: NamePrefix, NamePrefixBlacklist, NameWhitelist, MethodDefinitionMacros.
# NamePrefix: is_, has_, have_
# NamePrefixBlacklist: is_, has_, have_
# NameWhitelist: is_a?
# MethodDefinitionMacros: define_method, define_singleton_method
Naming/PredicateName:
  Exclude:
    - 'spec/**/*'
    - 'src/modules/Nis.rb'

# Offense count: 3
# Configuration parameters: MinNameLength, AllowNamesEndingInNumbers, AllowedNames, ForbiddenNames.
# AllowedNames: io, id, to, by, on, in, at, ip, db
Naming/MethodParameterName:
  Exclude:
    - 'src/include/nis/ui.rb'
    - 'src/modules/Nis.rb'

# Offense count: 6
Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'src/clients/add-on.rb'
    - 'src/clients/add-on_proposal.rb'
    - 'src/clients/inst_add-on_software.rb'
    - 'src/clients/vendor.rb'
    - 'src/include/add-on/add-on-workflow.rb'
    - 'src/include/add-on/misc.rb'
    - 'src/lib/add-on/clients/add-on_auto.rb'
    - 'src/modules/AddOnOthers.rb'
    - 'src/clients/nis-client.rb'
    - 'src/clients/nis.rb'
    - 'src/clients/nis_auto.rb'
    - 'src/include/nis/ui.rb'
    - 'src/modules/Nis.rb'

# Offense count: 3
# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Exclude:
    - 'src/include/nis/ui.rb'
    - 'src/modules/Nis.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: IncludeSemanticChanges.
Style/NonNilCheck:
  Exclude:
    - 'src/include/nis/ui.rb'
