#! /bin/bash
# $Id$
set -o errexit

AGENT=./ag_yp_conf
CASE=test-ypconf
AGPROG='YpConf ("'$CASE'-i.in")
Read (.)'
# kludge: break up the output into lines
S3='s/\([:,]\)/\1\
/g'
echo "$AGPROG" | $AGENT | sed -e 1d >$CASE.ycp.tmp
sed -e "$S3" $CASE.ycp.tmp > $CASE-i.out.tmp
diff -u $CASE-i.out $CASE-i.out.tmp

NORMALIZE="/home/mvidner/yast2/source/libycp/testsuite/parseycp -n"
#NORMALIZE="parseycp -n"

echo 'YpConf ("'$CASE'-o.out.tmp")
Write (.,' `$NORMALIZE $CASE.ycp.tmp` ')' \
    | $AGENT >/dev/null
diff -u $CASE-o.out $CASE-o.out.tmp
