#! /bin/bash
# $Id$
set -o errexit

AGENT=./ag_yp_conf
CASE=test-ypconf
AGPROG='YpConf ("'$CASE'-i.in")
Read (.)'
# kludge: break up the output into lines
S3='s/\([:,]\)/\1\
/g'
echo "$AGPROG" | $AGENT | sed -e 1d >$CASE.ycp.tmp
sed -e "$S3" $CASE.ycp.tmp > $CASE-i.out.tmp
diff -u $CASE-i.out.tmp $CASE-i.out

# the output contains newlines...
# cannot cope yet
exit

echo -n 'YpConf ("'$CASE'-o.out.tmp")
Write (.,' `cat $CASE.ycp.tmp` ')' \
    | $AGENT >/dev/null
diff -u $CASE-o.out.tmp $CASE-o.out
